version: "3.2"
services:
  rabbitmq_broker:
    build: 
      context: .
      dockerfile: ./RabbitMQ/Dockerfile
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ccpnetwork

  mcs_ventas:
    image: mcs_ventas:latest
    volumes:
        - ./Ventas/security.key/:/backend/security.key
        - ./Ventas/app-config.properties/:/backend/app-config.properties
        - ./Ventas/log_transactions_post.txt/:/backend/log_transactions_post.txt
        - ./Ventas/log_transactions_put.txt/:/backend/log_transactions_put.txt
    build: ./Ventas
    working_dir: /backend/
    command: python app.py
    container_name: mcs_ventas
    networks:
      - ccpnetwork
    depends_on: 
      - rabbitmq_broker

  mcs_registro_ventas_post:
    image: mcs_registro_ventas_post:latest
    volumes:
        - ./RegistroVentasPost/security.key/:/backend/security.key
        - ./RegistroVentasPost/log_post_orders.txt/:/backend/log_post_orders.txt
        - ./RegistroVentasPost/app-config.properties/:/backend/app-config.properties
    build: ./RegistroVentasPost
    working_dir: /backend/
    command: python app.py
    container_name: mcs_registro_ventas_post
    networks:
      - ccpnetwork
    depends_on: 
      - rabbitmq_broker

  mcs_registro_ventas_put:
    image: mcs_registro_ventas_put:latest
    volumes:
        - ./RegistroVentasPut/security.key/:/backend/security.key
        - ./RegistroVentasPut/app-data.json/:/backend/app-data.json
        - ./RegistroVentasPut/log_put_orders.txt/:/backend/log_put_orders.txt
        - ./RegistroVentasPut/app-config.properties/:/backend/app-config.properties
    build: ./RegistroVentasPut
    working_dir: /backend/
    command: python app.py
    container_name: mcs_registro_ventas_put
    networks:
      - ccpnetwork
    depends_on: 
      - rabbitmq_broker

  nginx_proxy_reverse:
    image: nginx:latest
    container_name: nginx_proxy_reverse
    ports:
        - 8080:8080
    volumes:
        - ./NginxProxyReverse/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ccpnetwork
    depends_on:
        - mcs_ventas        
        - mcs_registro_ventas_post
        - mcs_registro_ventas_put

networks: 
    ccpnetwork:
      driver: bridge