version: "3.2"
services:
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  mcs_ventas_01:
    image: mcs_ventas:latest
    volumes:
        - ./ventas/:/mnt/
    build: ./ventas
    working_dir: /backend/
    command: python base.py
    depends_on: 
      - redis

  mcs_ventas_02:
    image: mcs_ventas:latest
    volumes:
        - ./ventas/:/mnt/
    build: ./ventas
    working_dir: /backend/
    command: python base.py
    depends_on: 
      - redis

  mcs_ventas_03:
    image: mcs_ventas:latest
    volumes:
        - ./ventas/:/mnt/
    build: ./ventas
    working_dir: /backend/
    command: python base.py
    depends_on: 
      - redis

  mcs_registro_ventas:
    image: mcs_registro_ventas:latest
    volumes:
        - ./registroVentas/:/mnt/
    build: ./registroVentas
    working_dir: /backend/
    command: python base.py
    depends_on: 
      - redis

  nginx-balancer:
    image: nginx:latest
    ports:
        - 8080:8080
    volumes:
        - ./nginx-balancer/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - mcs_ventas_01
        - mcs_ventas_02
        - mcs_ventas_03        
        - mcs_registro_ventas
